# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin/cmake

# The command to remove a file.
RM = /nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nils/Docs/mistake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nils/Docs/mistake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nils/Docs/mistake/CMakeFiles /home/nils/Docs/mistake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nils/Docs/mistake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

imgui/backends/imgui_impl_opengl3.o: imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.o

# target to build an object file
imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_opengl3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.o

imgui/backends/imgui_impl_opengl3.i: imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_opengl3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.i

imgui/backends/imgui_impl_opengl3.s: imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_opengl3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.s

imgui/backends/imgui_impl_sdl3.o: imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl3.o

# target to build an object file
imgui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_sdl3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl3.cpp.o

imgui/backends/imgui_impl_sdl3.i: imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_sdl3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl3.cpp.i

imgui/backends/imgui_impl_sdl3.s: imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_sdl3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl3.cpp.s

imgui/backends/imgui_impl_sdlrenderer3.o: imgui/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdlrenderer3.o

# target to build an object file
imgui/backends/imgui_impl_sdlrenderer3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_sdlrenderer3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdlrenderer3.cpp.o

imgui/backends/imgui_impl_sdlrenderer3.i: imgui/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdlrenderer3.i

# target to preprocess a source file
imgui/backends/imgui_impl_sdlrenderer3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_sdlrenderer3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdlrenderer3.cpp.i

imgui/backends/imgui_impl_sdlrenderer3.s: imgui/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdlrenderer3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_sdlrenderer3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/backends/imgui_impl_sdlrenderer3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdlrenderer3.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_demo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_demo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_demo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_draw.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_draw.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_draw.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_widgets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_widgets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/imgui/imgui_widgets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

src/editor.o: src/editor.cpp.o
.PHONY : src/editor.o

# target to build an object file
src/editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/editor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/editor.cpp.o
.PHONY : src/editor.cpp.o

src/editor.i: src/editor.cpp.i
.PHONY : src/editor.i

# target to preprocess a source file
src/editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/editor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/editor.cpp.i
.PHONY : src/editor.cpp.i

src/editor.s: src/editor.cpp.s
.PHONY : src/editor.s

# target to generate assembly for a file
src/editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/editor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/editor.cpp.s
.PHONY : src/editor.cpp.s

src/frustumCulling.o: src/frustumCulling.cpp.o
.PHONY : src/frustumCulling.o

# target to build an object file
src/frustumCulling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/frustumCulling.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/frustumCulling.cpp.o
.PHONY : src/frustumCulling.cpp.o

src/frustumCulling.i: src/frustumCulling.cpp.i
.PHONY : src/frustumCulling.i

# target to preprocess a source file
src/frustumCulling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/frustumCulling.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/frustumCulling.cpp.i
.PHONY : src/frustumCulling.cpp.i

src/frustumCulling.s: src/frustumCulling.cpp.s
.PHONY : src/frustumCulling.s

# target to generate assembly for a file
src/frustumCulling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/frustumCulling.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/frustumCulling.cpp.s
.PHONY : src/frustumCulling.cpp.s

src/geometry.o: src/geometry.cpp.o
.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i
.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s
.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/imgui-gruvbox.o: src/imgui-gruvbox.cpp.o
.PHONY : src/imgui-gruvbox.o

# target to build an object file
src/imgui-gruvbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/imgui-gruvbox.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/imgui-gruvbox.cpp.o
.PHONY : src/imgui-gruvbox.cpp.o

src/imgui-gruvbox.i: src/imgui-gruvbox.cpp.i
.PHONY : src/imgui-gruvbox.i

# target to preprocess a source file
src/imgui-gruvbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/imgui-gruvbox.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/imgui-gruvbox.cpp.i
.PHONY : src/imgui-gruvbox.cpp.i

src/imgui-gruvbox.s: src/imgui-gruvbox.cpp.s
.PHONY : src/imgui-gruvbox.s

# target to generate assembly for a file
src/imgui-gruvbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/imgui-gruvbox.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/imgui-gruvbox.cpp.s
.PHONY : src/imgui-gruvbox.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/mesh.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/mesh.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/mesh.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/obj_loader.o: src/obj_loader.cpp.o
.PHONY : src/obj_loader.o

# target to build an object file
src/obj_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/obj_loader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/obj_loader.cpp.o
.PHONY : src/obj_loader.cpp.o

src/obj_loader.i: src/obj_loader.cpp.i
.PHONY : src/obj_loader.i

# target to preprocess a source file
src/obj_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/obj_loader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/obj_loader.cpp.i
.PHONY : src/obj_loader.cpp.i

src/obj_loader.s: src/obj_loader.cpp.s
.PHONY : src/obj_loader.s

# target to generate assembly for a file
src/obj_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/obj_loader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/obj_loader.cpp.s
.PHONY : src/obj_loader.cpp.s

src/objdefs.o: src/objdefs.cpp.o
.PHONY : src/objdefs.o

# target to build an object file
src/objdefs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/objdefs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/objdefs.cpp.o
.PHONY : src/objdefs.cpp.o

src/objdefs.i: src/objdefs.cpp.i
.PHONY : src/objdefs.i

# target to preprocess a source file
src/objdefs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/objdefs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/objdefs.cpp.i
.PHONY : src/objdefs.cpp.i

src/objdefs.s: src/objdefs.cpp.s
.PHONY : src/objdefs.s

# target to generate assembly for a file
src/objdefs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/objdefs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/objdefs.cpp.s
.PHONY : src/objdefs.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/renderer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/renderer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/renderer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/shader-utils.o: src/shader-utils.cpp.o
.PHONY : src/shader-utils.o

# target to build an object file
src/shader-utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/shader-utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/shader-utils.cpp.o
.PHONY : src/shader-utils.cpp.o

src/shader-utils.i: src/shader-utils.cpp.i
.PHONY : src/shader-utils.i

# target to preprocess a source file
src/shader-utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/shader-utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/shader-utils.cpp.i
.PHONY : src/shader-utils.cpp.i

src/shader-utils.s: src/shader-utils.cpp.s
.PHONY : src/shader-utils.s

# target to generate assembly for a file
src/shader-utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/shader-utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/shader-utils.cpp.s
.PHONY : src/shader-utils.cpp.s

src/unit-tests.o: src/unit-tests.cpp.o
.PHONY : src/unit-tests.o

# target to build an object file
src/unit-tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/unit-tests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/unit-tests.cpp.o
.PHONY : src/unit-tests.cpp.o

src/unit-tests.i: src/unit-tests.cpp.i
.PHONY : src/unit-tests.i

# target to preprocess a source file
src/unit-tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/unit-tests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/unit-tests.cpp.i
.PHONY : src/unit-tests.cpp.i

src/unit-tests.s: src/unit-tests.cpp.s
.PHONY : src/unit-tests.s

# target to generate assembly for a file
src/unit-tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/src/unit-tests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/unit-tests.cpp.s
.PHONY : src/unit-tests.cpp.s

tests/unit-tests.o: tests/unit-tests.cpp.o
.PHONY : tests/unit-tests.o

# target to build an object file
tests/unit-tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/unit-tests.cpp.o
.PHONY : tests/unit-tests.cpp.o

tests/unit-tests.i: tests/unit-tests.cpp.i
.PHONY : tests/unit-tests.i

# target to preprocess a source file
tests/unit-tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/unit-tests.cpp.i
.PHONY : tests/unit-tests.cpp.i

tests/unit-tests.s: tests/unit-tests.cpp.s
.PHONY : tests/unit-tests.s

# target to generate assembly for a file
tests/unit-tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/unit-tests.cpp.s
.PHONY : tests/unit-tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... clean-all"
	@echo "... run"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... app"
	@echo "... unit-tests"
	@echo "... imgui/backends/imgui_impl_opengl3.o"
	@echo "... imgui/backends/imgui_impl_opengl3.i"
	@echo "... imgui/backends/imgui_impl_opengl3.s"
	@echo "... imgui/backends/imgui_impl_sdl3.o"
	@echo "... imgui/backends/imgui_impl_sdl3.i"
	@echo "... imgui/backends/imgui_impl_sdl3.s"
	@echo "... imgui/backends/imgui_impl_sdlrenderer3.o"
	@echo "... imgui/backends/imgui_impl_sdlrenderer3.i"
	@echo "... imgui/backends/imgui_impl_sdlrenderer3.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... src/editor.o"
	@echo "... src/editor.i"
	@echo "... src/editor.s"
	@echo "... src/frustumCulling.o"
	@echo "... src/frustumCulling.i"
	@echo "... src/frustumCulling.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/imgui-gruvbox.o"
	@echo "... src/imgui-gruvbox.i"
	@echo "... src/imgui-gruvbox.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/obj_loader.o"
	@echo "... src/obj_loader.i"
	@echo "... src/obj_loader.s"
	@echo "... src/objdefs.o"
	@echo "... src/objdefs.i"
	@echo "... src/objdefs.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/shader-utils.o"
	@echo "... src/shader-utils.i"
	@echo "... src/shader-utils.s"
	@echo "... src/unit-tests.o"
	@echo "... src/unit-tests.i"
	@echo "... src/unit-tests.s"
	@echo "... tests/unit-tests.o"
	@echo "... tests/unit-tests.i"
	@echo "... tests/unit-tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

